//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AVAResource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AVAResource.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions Description.
        /// </summary>
        public static string ActionDescription {
            get {
                return ResourceManager.GetString("ActionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air Filter Changed.
        /// </summary>
        public static string AirFilterChanged {
            get {
                return ResourceManager.GetString("AirFilterChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Amount Paid.
        /// </summary>
        public static string AllAmountPaid {
            get {
                return ResourceManager.GetString("AllAmountPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Volume Fuel.
        /// </summary>
        public static string AllVolumeFuel {
            get {
                return ResourceManager.GetString("AllVolumeFuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Paid.
        /// </summary>
        public static string AmountPaid {
            get {
                return ResourceManager.GetString("AmountPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendances.
        /// </summary>
        public static string Attendances {
            get {
                return ResourceManager.GetString("Attendances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automobile.
        /// </summary>
        public static string Automobile {
            get {
                return ResourceManager.GetString("Automobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define Model.
        /// </summary>
        public static string AutomobileClass_Define {
            get {
                return ResourceManager.GetString("AutomobileClass_Define", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Model.
        /// </summary>
        public static string AutomobileClass_Delete {
            get {
                return ResourceManager.GetString("AutomobileClass_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Model.
        /// </summary>
        public static string AutomobileClass_Edit {
            get {
                return ResourceManager.GetString("AutomobileClass_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Model.
        /// </summary>
        public static string AutomobileClass_List {
            get {
                return ResourceManager.GetString("AutomobileClass_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automobile.
        /// </summary>
        public static string AutomobileMngMenu {
            get {
                return ResourceManager.GetString("AutomobileMngMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics Analysis.
        /// </summary>
        public static string AutomobileStatisticsAnalysis {
            get {
                return ResourceManager.GetString("AutomobileStatisticsAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buyer.
        /// </summary>
        public static string Buyer_TrafficCard {
            get {
                return ResourceManager.GetString("Buyer_TrafficCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oil Change Date.
        /// </summary>
        public static string ChangeDate {
            get {
                return ResourceManager.GetString("ChangeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart Deliver Automobile.
        /// </summary>
        public static string Chart_Deliver_Automobile {
            get {
                return ResourceManager.GetString("Chart_Deliver_Automobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقایسه سوخت با مسافت.
        /// </summary>
        public static string Chart_Fuel_Distance {
            get {
                return ResourceManager.GetString("Chart_Fuel_Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart Repair Automobile.
        /// </summary>
        public static string Chart_Repair_Automobile {
            get {
                return ResourceManager.GetString("Chart_Repair_Automobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repair Workshop Referral.
        /// </summary>
        public static string Chart_RepairWorkshop_Referral {
            get {
                return ResourceManager.GetString("Chart_RepairWorkshop_Referral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقایسه هزینه خرید به تعمیر.
        /// </summary>
        public static string Chart_Repiar_Buy {
            get {
                return ResourceManager.GetString("Chart_Repiar_Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسافت اداره ها.
        /// </summary>
        public static string ChartTransitDepartmentDistance {
            get {
                return ResourceManager.GetString("ChartTransitDepartmentDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسافت راننده ها.
        /// </summary>
        public static string ChartTransitDriverDistance {
            get {
                return ResourceManager.GetString("ChartTransitDriverDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chassis Not Unique.
        /// </summary>
        public static string Chassis_Not_Unique {
            get {
                return ResourceManager.GetString("Chassis_Not_Unique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Define.
        /// </summary>
        public static string Color_Define {
            get {
                return ResourceManager.GetString("Color_Define", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Delete.
        /// </summary>
        public static string Color_Delete {
            get {
                return ResourceManager.GetString("Color_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Edit.
        /// </summary>
        public static string Color_Edit {
            get {
                return ResourceManager.GetString("Color_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color of List.
        /// </summary>
        public static string Color_List {
            get {
                return ResourceManager.GetString("Color_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Name.
        /// </summary>
        public static string Color_Name {
            get {
                return ResourceManager.GetString("Color_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Value.
        /// </summary>
        public static string Color_Value {
            get {
                return ResourceManager.GetString("Color_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commander Person.
        /// </summary>
        public static string CommanderPerson {
            get {
                return ResourceManager.GetString("CommanderPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumable Part.
        /// </summary>
        public static string ConsumablePart {
            get {
                return ResourceManager.GetString("ConsumablePart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string DashboardMenu {
            get {
                return ResourceManager.GetString("DashboardMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Buy.
        /// </summary>
        public static string DateBuy_TrafficCard {
            get {
                return ResourceManager.GetString("DateBuy_TrafficCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Expire.
        /// </summary>
        public static string DateExpire_TrafficCard {
            get {
                return ResourceManager.GetString("DateExpire_TrafficCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date ReFual.
        /// </summary>
        public static string DateReFual {
            get {
                return ResourceManager.GetString("DateReFual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Repair.
        /// </summary>
        public static string DateRepair {
            get {
                return ResourceManager.GetString("DateRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define Driver.
        /// </summary>
        public static string Define_Driver {
            get {
                return ResourceManager.GetString("Define_Driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define FuelCard.
        /// </summary>
        public static string Define_FuelCard {
            get {
                return ResourceManager.GetString("Define_FuelCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define FuelConsume.
        /// </summary>
        public static string Define_FuelConsume {
            get {
                return ResourceManager.GetString("Define_FuelConsume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define OilChange.
        /// </summary>
        public static string Define_OilChange {
            get {
                return ResourceManager.GetString("Define_OilChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define Repair.
        /// </summary>
        public static string Define_Repair {
            get {
                return ResourceManager.GetString("Define_Repair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define TrafficCard.
        /// </summary>
        public static string Define_TrafficCard {
            get {
                return ResourceManager.GetString("Define_TrafficCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define Automobile.
        /// </summary>
        public static string DefineAutomobile {
            get {
                return ResourceManager.GetString("DefineAutomobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define Incident.
        /// </summary>
        public static string DefineIncident {
            get {
                return ResourceManager.GetString("DefineIncident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Driver.
        /// </summary>
        public static string Delete_Driver {
            get {
                return ResourceManager.GetString("Delete_Driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete FuelCard.
        /// </summary>
        public static string Delete_FuelCard {
            get {
                return ResourceManager.GetString("Delete_FuelCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete FuelConsume.
        /// </summary>
        public static string Delete_FuelConsume {
            get {
                return ResourceManager.GetString("Delete_FuelConsume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete OilChange.
        /// </summary>
        public static string Delete_OilChange {
            get {
                return ResourceManager.GetString("Delete_OilChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Repair.
        /// </summary>
        public static string Delete_Repair {
            get {
                return ResourceManager.GetString("Delete_Repair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete TrafficCard.
        /// </summary>
        public static string Delete_TrafficCard {
            get {
                return ResourceManager.GetString("Delete_TrafficCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Automobile.
        /// </summary>
        public static string DeleteAutomobile {
            get {
                return ResourceManager.GetString("DeleteAutomobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Driver by Name.
        /// </summary>
        public static string DeleteDriver {
            get {
                return ResourceManager.GetString("DeleteDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Incident.
        /// </summary>
        public static string DeleteIncident {
            get {
                return ResourceManager.GetString("DeleteIncident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteRepair.
        /// </summary>
        public static string DeleteRepair {
            get {
                return ResourceManager.GetString("DeleteRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteTransit.
        /// </summary>
        public static string DeleteTransit {
            get {
                return ResourceManager.GetString("DeleteTransit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Date.
        /// </summary>
        public static string DeliveryDate {
            get {
                return ResourceManager.GetString("DeliveryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Department.
        /// </summary>
        public static string DeliveryDepartment {
            get {
                return ResourceManager.GetString("DeliveryDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Hour.
        /// </summary>
        public static string DeliveryHour {
            get {
                return ResourceManager.GetString("DeliveryHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Minute.
        /// </summary>
        public static string DeliveryMinute {
            get {
                return ResourceManager.GetString("DeliveryMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define Department.
        /// </summary>
        public static string Department_Define {
            get {
                return ResourceManager.GetString("Department_Define", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Department.
        /// </summary>
        public static string Department_Delete {
            get {
                return ResourceManager.GetString("Department_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Department.
        /// </summary>
        public static string Department_Edit {
            get {
                return ResourceManager.GetString("Department_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department of List.
        /// </summary>
        public static string DepartmentHeaderList {
            get {
                return ResourceManager.GetString("DepartmentHeaderList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Name.
        /// </summary>
        public static string DepartmentName {
            get {
                return ResourceManager.GetString("DepartmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ltr.
        /// </summary>
        public static string dir {
            get {
                return ResourceManager.GetString("dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        public static string Distance {
            get {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance Befor ReFual.
        /// </summary>
        public static string DistanceBeforReFual {
            get {
                return ResourceManager.GetString("DistanceBeforReFual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver.
        /// </summary>
        public static string Driver {
            get {
                return ResourceManager.GetString("Driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver List.
        /// </summary>
        public static string DriverHeaderList {
            get {
                return ResourceManager.GetString("DriverHeaderList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Driver.
        /// </summary>
        public static string Edit_Driver {
            get {
                return ResourceManager.GetString("Edit_Driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit FuelCard.
        /// </summary>
        public static string Edit_FuelCard {
            get {
                return ResourceManager.GetString("Edit_FuelCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit FuelConsume.
        /// </summary>
        public static string Edit_FuelConsume {
            get {
                return ResourceManager.GetString("Edit_FuelConsume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit OilChange.
        /// </summary>
        public static string Edit_OilChange {
            get {
                return ResourceManager.GetString("Edit_OilChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Repair.
        /// </summary>
        public static string Edit_Repair {
            get {
                return ResourceManager.GetString("Edit_Repair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit TrafficCard.
        /// </summary>
        public static string Edit_TrafficCard {
            get {
                return ResourceManager.GetString("Edit_TrafficCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Automobile.
        /// </summary>
        public static string EditAutomobile {
            get {
                return ResourceManager.GetString("EditAutomobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Incident.
        /// </summary>
        public static string EditIncident {
            get {
                return ResourceManager.GetString("EditIncident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Repair.
        /// </summary>
        public static string EditRepair {
            get {
                return ResourceManager.GetString("EditRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Transit.
        /// </summary>
        public static string EditTransit {
            get {
                return ResourceManager.GetString("EditTransit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En.
        /// </summary>
        public static string Englis {
            get {
                return ResourceManager.GetString("Englis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Attendances.
        /// </summary>
        public static string EnterAttendances {
            get {
                return ResourceManager.GetString("EnterAttendances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fa.
        /// </summary>
        public static string Farsi {
            get {
                return ResourceManager.GetString("Farsi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fual Consume.
        /// </summary>
        public static string FualConsume {
            get {
                return ResourceManager.GetString("FualConsume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fual Station.
        /// </summary>
        public static string FualStation {
            get {
                return ResourceManager.GetString("FualStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FuelCard of List.
        /// </summary>
        public static string FuelCardHeaderList {
            get {
                return ResourceManager.GetString("FuelCardHeaderList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel Card Number.
        /// </summary>
        public static string FuelCardNumber {
            get {
                return ResourceManager.GetString("FuelCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel.
        /// </summary>
        public static string FuelMngMenu {
            get {
                return ResourceManager.GetString("FuelMngMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel ReportCompare .
        /// </summary>
        public static string FuelReportCompareMngMenu {
            get {
                return ResourceManager.GetString("FuelReportCompareMngMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour.
        /// </summary>
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incident Damages.
        /// </summary>
        public static string IncidentDamages {
            get {
                return ResourceManager.GetString("IncidentDamages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incident Date.
        /// </summary>
        public static string IncidentDate {
            get {
                return ResourceManager.GetString("IncidentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define Incident.
        /// </summary>
        public static string IncidentDefine {
            get {
                return ResourceManager.GetString("IncidentDefine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Incident.
        /// </summary>
        public static string IncidentDelete {
            get {
                return ResourceManager.GetString("IncidentDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incident Description.
        /// </summary>
        public static string IncidentDescription {
            get {
                return ResourceManager.GetString("IncidentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incident Driver.
        /// </summary>
        public static string IncidentDriver {
            get {
                return ResourceManager.GetString("IncidentDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Incident.
        /// </summary>
        public static string IncidentEdit {
            get {
                return ResourceManager.GetString("IncidentEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Incident.
        /// </summary>
        public static string IncidentHeaderList {
            get {
                return ResourceManager.GetString("IncidentHeaderList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IncidentHour.
        /// </summary>
        public static string IncidentHour {
            get {
                return ResourceManager.GetString("IncidentHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Incident.
        /// </summary>
        public static string IncidentList {
            get {
                return ResourceManager.GetString("IncidentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IncidentMinute.
        /// </summary>
        public static string IncidentMinute {
            get {
                return ResourceManager.GetString("IncidentMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incident.
        /// </summary>
        public static string IncidentMngMenu {
            get {
                return ResourceManager.GetString("IncidentMngMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incident Repair.
        /// </summary>
        public static string IncidentRepair {
            get {
                return ResourceManager.GetString("IncidentRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to input-icon-right.
        /// </summary>
        public static string Input_icon {
            get {
                return ResourceManager.GetString("Input_icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password.
        /// </summary>
        public static string Invalid_username_or_password {
            get {
                return ResourceManager.GetString("Invalid_username_or_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice No.
        /// </summary>
        public static string InvoiceNo {
            get {
                return ResourceManager.GetString("InvoiceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Driver.
        /// </summary>
        public static string List_Driver {
            get {
                return ResourceManager.GetString("List_Driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List FuelConsume.
        /// </summary>
        public static string List_FuelConsume {
            get {
                return ResourceManager.GetString("List_FuelConsume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List OilChange.
        /// </summary>
        public static string List_OilChange {
            get {
                return ResourceManager.GetString("List_OilChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogOff.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automobile Model.
        /// </summary>
        public static string Menu_AutomobileClass {
            get {
                return ResourceManager.GetString("Menu_AutomobileClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Menu_Color {
            get {
                return ResourceManager.GetString("Menu_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departments.
        /// </summary>
        public static string Menu_Department {
            get {
                return ResourceManager.GetString("Menu_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drivers.
        /// </summary>
        public static string Menu_Driver {
            get {
                return ResourceManager.GetString("Menu_Driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel Card.
        /// </summary>
        public static string Menu_FuelCard {
            get {
                return ResourceManager.GetString("Menu_FuelCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fundmental Info.
        /// </summary>
        public static string Menu_FundmentalInfo {
            get {
                return ResourceManager.GetString("Menu_FundmentalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traffic Card.
        /// </summary>
        public static string Menu_TrafficCard {
            get {
                return ResourceManager.GetString("Menu_TrafficCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automobil management system.
        /// </summary>
        public static string message {
            get {
                return ResourceManager.GetString("message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mileag After Trip.
        /// </summary>
        public static string MileagAfterTrip {
            get {
                return ResourceManager.GetString("MileagAfterTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mileag Before Trip.
        /// </summary>
        public static string MileagBeforeTrip {
            get {
                return ResourceManager.GetString("MileagBeforeTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute.
        /// </summary>
        public static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chassis Number.
        /// </summary>
        public static string Mobil_Chassis {
            get {
                return ResourceManager.GetString("Mobil_Chassis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance Department.
        /// </summary>
        public static string Mobil_Maintenance_Department {
            get {
                return ResourceManager.GetString("Mobil_Maintenance_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plaque Number.
        /// </summary>
        public static string Mobil_Plaque {
            get {
                return ResourceManager.GetString("Mobil_Plaque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Mobile_Color {
            get {
                return ResourceManager.GetString("Mobile_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Bur.
        /// </summary>
        public static string Mobile_Date_Buy {
            get {
                return ResourceManager.GetString("Mobile_Date_Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        public static string Mobile_Distance {
            get {
                return ResourceManager.GetString("Mobile_Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fual Consume per kilometer.
        /// </summary>
        public static string Mobile_Fual_Consum {
            get {
                return ResourceManager.GetString("Mobile_Fual_Consum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fual Type.
        /// </summary>
        public static string Mobile_Fual_Type {
            get {
                return ResourceManager.GetString("Mobile_Fual_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Automobile.
        /// </summary>
        public static string Mobile_Header_Grid {
            get {
                return ResourceManager.GetString("Mobile_Header_Grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Mobile_Image {
            get {
                return ResourceManager.GetString("Mobile_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Service.
        /// </summary>
        public static string Mobile_Last_Service {
            get {
                return ResourceManager.GetString("Mobile_Last_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model .
        /// </summary>
        public static string Mobile_Model {
            get {
                return ResourceManager.GetString("Mobile_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Mobile_Price {
            get {
                return ResourceManager.GetString("Mobile_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produce Year.
        /// </summary>
        public static string Mobile_Produce_Year {
            get {
                return ResourceManager.GetString("Mobile_Produce_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automobile Status.
        /// </summary>
        public static string Mobile_Status {
            get {
                return ResourceManager.GetString("Mobile_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Tank.
        /// </summary>
        public static string Mobile_Volume_Tank {
            get {
                return ResourceManager.GetString("Mobile_Volume_Tank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Driver.
        /// </summary>
        public static string NameDriver {
            get {
                return ResourceManager.GetString("NameDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Change Destination.
        /// </summary>
        public static string NextChangeDest {
            get {
                return ResourceManager.GetString("NextChangeDest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number FuelCard.
        /// </summary>
        public static string Number_FuelCard {
            get {
                return ResourceManager.GetString("Number_FuelCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Card.
        /// </summary>
        public static string NumberCard_TrafficCard {
            get {
                return ResourceManager.GetString("NumberCard_TrafficCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Oil_Driver {
            get {
                return ResourceManager.GetString("Oil_Driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OilChange.
        /// </summary>
        public static string OilChangeMngMenu {
            get {
                return ResourceManager.GetString("OilChangeMngMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oil Filter Changed.
        /// </summary>
        public static string OilFilterChanged {
            get {
                return ResourceManager.GetString("OilFilterChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part Name.
        /// </summary>
        public static string PartName {
            get {
                return ResourceManager.GetString("PartName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string PartPrice {
            get {
                return ResourceManager.GetString("PartPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part Type.
        /// </summary>
        public static string PartType {
            get {
                return ResourceManager.GetString("PartType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Pass {
            get {
                return ResourceManager.GetString("Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Type.
        /// </summary>
        public static string PaymentType {
            get {
                return ResourceManager.GetString("PaymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Number.
        /// </summary>
        public static string PersonalNumber {
            get {
                return ResourceManager.GetString("PersonalNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Your Information.
        /// </summary>
        public static string Please_Enter_Your_Information {
            get {
                return ResourceManager.GetString("Please_Enter_Your_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pull-left.
        /// </summary>
        public static string Pull_Dir {
            get {
                return ResourceManager.GetString("Pull_Dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real Fual Consume.
        /// </summary>
        public static string RealFualConsume {
            get {
                return ResourceManager.GetString("RealFualConsume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegisterRepair.
        /// </summary>
        public static string RegisterRepair {
            get {
                return ResourceManager.GetString("RegisterRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Transit.
        /// </summary>
        public static string RegisterTransit {
            get {
                return ResourceManager.GetString("RegisterTransit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrar User.
        /// </summary>
        public static string RegistrarUser {
            get {
                return ResourceManager.GetString("RegistrarUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string Remember_Me {
            get {
                return ResourceManager.GetString("Remember_Me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Repair.
        /// </summary>
        public static string Repair_Header_List {
            get {
                return ResourceManager.GetString("Repair_Header_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        public static string RepairCost {
            get {
                return ResourceManager.GetString("RepairCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repairman Description.
        /// </summary>
        public static string RepairmanDescription {
            get {
                return ResourceManager.GetString("RepairmanDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repairment.
        /// </summary>
        public static string RepairMngMenu {
            get {
                return ResourceManager.GetString("RepairMngMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Date.
        /// </summary>
        public static string ReturnDate {
            get {
                return ResourceManager.GetString("ReturnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Hour.
        /// </summary>
        public static string ReturnHour {
            get {
                return ResourceManager.GetString("ReturnHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Minute.
        /// </summary>
        public static string ReturnMinute {
            get {
                return ResourceManager.GetString("ReturnMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchHeader {
            get {
                return ResourceManager.GetString("SearchHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        public static string SettingMngMenu {
            get {
                return ResourceManager.GetString("SettingMngMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You successfully read this important alert message..
        /// </summary>
        public static string SuccessMessage {
            get {
                return ResourceManager.GetString("SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Title.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of TrafficCard.
        /// </summary>
        public static string TrafficCard_Header_List {
            get {
                return ResourceManager.GetString("TrafficCard_Header_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TrafficCard.
        /// </summary>
        public static string TrafficCardMngMenu {
            get {
                return ResourceManager.GetString("TrafficCardMngMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Type Card.
        /// </summary>
        public static string TrafficCardType_TrafficCard {
            get {
                return ResourceManager.GetString("TrafficCardType_TrafficCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transit of Automobiles.
        /// </summary>
        public static string TransitHeaderList {
            get {
                return ResourceManager.GetString("TransitHeaderList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transit .
        /// </summary>
        public static string TransitMngMenu {
            get {
                return ResourceManager.GetString("TransitMngMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transit Report Distance.
        /// </summary>
        public static string TransitReportDisMngMenu {
            get {
                return ResourceManager.GetString("TransitReportDisMngMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transit Report.
        /// </summary>
        public static string TransitReportMngMenu {
            get {
                return ResourceManager.GetString("TransitReportMngMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transit UnDelivery .
        /// </summary>
        public static string TransitUnDeliveryMenu {
            get {
                return ResourceManager.GetString("TransitUnDeliveryMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of oil.
        /// </summary>
        public static string TypeOil {
            get {
                return ResourceManager.GetString("TypeOil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string User_ConfirmPass {
            get {
                return ResourceManager.GetString("User_ConfirmPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string User_Email {
            get {
                return ResourceManager.GetString("User_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string User_FirstName {
            get {
                return ResourceManager.GetString("User_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string User_LastName {
            get {
                return ResourceManager.GetString("User_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission of user.
        /// </summary>
        public static string User_RoleHeader {
            get {
                return ResourceManager.GetString("User_RoleHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Type.
        /// </summary>
        public static string User_Type {
            get {
                return ResourceManager.GetString("User_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Management .
        /// </summary>
        public static string UserMngMenu {
            get {
                return ResourceManager.GetString("UserMngMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Number.
        /// </summary>
        public static string UserNumber {
            get {
                return ResourceManager.GetString("UserNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Fuel.
        /// </summary>
        public static string VolumeFuel {
            get {
                return ResourceManager.GetString("VolumeFuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wage.
        /// </summary>
        public static string Wage {
            get {
                return ResourceManager.GetString("Wage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error in action.
        /// </summary>
        public static string WarningMessage {
            get {
                return ResourceManager.GetString("WarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workshop.
        /// </summary>
        public static string Workshop {
            get {
                return ResourceManager.GetString("Workshop", resourceCulture);
            }
        }
    }
}
